#!/usr/bin/env python3
"""
Diff two requirements.md files generated by scripts/generate-requirements.sh
and emit a PR-comment-friendly markdown summary on stdout.

Usage:
  scripts/diff_requirements.py BASE_FILE HEAD_FILE

The single-backtick escape in id rendering uses raw triple quotes below where
needed; this module-level docstring is plain text.

What it surfaces:
  - Added requirements (new FR/NFR/INV/CON ids in HEAD)
  - Removed requirements (ids gone from HEAD)
  - Modified spec (same id, different Given/When/Then or ADR/US link)
  - Coverage line changes (count, % with spec)
  - For the by-us file: User Story coverage delta (US implemented/unimplemented)

Why this exists: a reviewer should see, at PR review time, what the test suite
NOW says the system must do that it didn't before, without having to eyeball a
756-line markdown diff. The summary lands as a comment on the PR.
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


REQ_HEADER_RE = re.compile(r"^####\s+`([^`]+)`\s*$", re.MULTILINE)
BULLET_RE = re.compile(r"^-\s+\*\*(\w+)\*\*:\s+(.*)$", re.MULTILINE)
COVERAGE_TOTAL_RE = re.compile(r"^-\s+Total tests scanned:\s+\*\*(\d+)\*\*", re.MULTILINE)
COVERAGE_SPECD_RE = re.compile(r"^-\s+With complete spec javadoc:\s+\*\*(\d+)\*\*", re.MULTILINE)
US_DECLARED_RE = re.compile(r"^-\s+User Stories declared in PRODUCT\.md:\s+\*\*(\d+)\*\*", re.MULTILINE)
US_LINKED_RE = re.compile(r"^-\s+User Stories with at least one linked test:\s+\*\*(\d+)\*\*", re.MULTILINE)
US_NOT_IMPL_RE = re.compile(r"^-\s+User Stories declared but \*\*not yet implemented\*\*:\s+\*\*(\d+)\*\*", re.MULTILINE)


@dataclass(frozen=True)
class Requirement:
    id: str
    given: str
    when: str
    then: str
    adr: str
    us: str

    def spec_tuple(self) -> tuple[str, str, str, str, str]:
        return (self.given, self.when, self.then, self.adr, self.us)


def parse_requirements(text: str) -> dict[str, Requirement]:
    r"""
    Split the requirements.md by `#### \`<id>\`` headers and pull the bullet
    fields from each block. Returns id -> Requirement.
    """
    # find all (id, start, end) windows
    headers = list(REQ_HEADER_RE.finditer(text))
    out: dict[str, Requirement] = {}
    for i, m in enumerate(headers):
        req_id = m.group(1)
        start = m.end()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        block = text[start:end]
        bullets = {k: v.strip() for k, v in BULLET_RE.findall(block)}
        out[req_id] = Requirement(
            id=req_id,
            given=bullets.get("Given", ""),
            when=bullets.get("When", ""),
            then=bullets.get("Then", ""),
            adr=bullets.get("ADR", ""),
            us=bullets.get("User Story", ""),
        )
    return out


def parse_coverage(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for name, regex in (
        ("total", COVERAGE_TOTAL_RE),
        ("specd", COVERAGE_SPECD_RE),
        ("us_declared", US_DECLARED_RE),
        ("us_linked", US_LINKED_RE),
        ("us_not_impl", US_NOT_IMPL_RE),
    ):
        m = regex.search(text)
        if m:
            out[name] = int(m.group(1))
    return out


def fmt_delta(label: str, base: int, head: int) -> str:
    delta = head - base
    sign = "" if delta == 0 else (f" (+{delta})" if delta > 0 else f" ({delta})")
    return f"{label}: **{head}**{sign}"


def render_diff(base: dict[str, Requirement], head: dict[str, Requirement],
                base_cov: dict[str, int], head_cov: dict[str, int]) -> str:
    base_ids = set(base.keys())
    head_ids = set(head.keys())

    added = sorted(head_ids - base_ids)
    removed = sorted(base_ids - head_ids)
    modified = sorted(
        rid for rid in (base_ids & head_ids)
        if base[rid].spec_tuple() != head[rid].spec_tuple()
    )

    lines: list[str] = []
    lines.append("## Requirements diff")
    lines.append("")
    if not added and not removed and not modified:
        lines.append("_No requirements added, removed, or modified by this PR._")
    else:
        lines.append(
            f"**+{len(added)} added · -{len(removed)} removed · "
            f"~{len(modified)} modified**"
        )
    lines.append("")

    lines.append("### Coverage")
    lines.append("")
    if base_cov.get("total") is not None and head_cov.get("total") is not None:
        lines.append(f"- {fmt_delta('Total tests', base_cov.get('total', 0), head_cov.get('total', 0))}")
        lines.append(f"- {fmt_delta('With complete spec javadoc', base_cov.get('specd', 0), head_cov.get('specd', 0))}")
        if "us_declared" in head_cov or "us_declared" in base_cov:
            lines.append(f"- {fmt_delta('User Stories declared (PRODUCT.md)', base_cov.get('us_declared', 0), head_cov.get('us_declared', 0))}")
            lines.append(f"- {fmt_delta('User Stories linked to a test', base_cov.get('us_linked', 0), head_cov.get('us_linked', 0))}")
            lines.append(f"- {fmt_delta('User Stories NOT yet implemented', base_cov.get('us_not_impl', 0), head_cov.get('us_not_impl', 0))}")
    lines.append("")

    if added:
        lines.append("### Added")
        lines.append("")
        for rid in added:
            r = head[rid]
            lines.append(f"- **`{rid}`**")
            if r.given or r.when or r.then:
                if r.given: lines.append(f"  - Given: {r.given}")
                if r.when:  lines.append(f"  - When: {r.when}")
                if r.then:  lines.append(f"  - Then: {r.then}")
            else:
                lines.append("  - _(spec missing)_")
        lines.append("")

    if removed:
        lines.append("### Removed")
        lines.append("")
        for rid in removed:
            lines.append(f"- `{rid}`")
        lines.append("")

    if modified:
        lines.append("### Modified spec")
        lines.append("")
        for rid in modified:
            lines.append(f"- **`{rid}`**")
            b, h = base[rid], head[rid]
            for label, ba, ha in (
                ("Given", b.given, h.given),
                ("When", b.when, h.when),
                ("Then", b.then, h.then),
                ("ADR", b.adr, h.adr),
                ("US", b.us, h.us),
            ):
                if ba != ha:
                    lines.append(f"  - {label}:")
                    if ba: lines.append(f"    - before: {ba}")
                    if ha: lines.append(f"    - after:  {ha}")
                    if not ba: lines.append("    - before: _(empty)_")
                    if not ha: lines.append("    - after:  _(empty)_")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(f"usage: {argv[0]} BASE_FILE HEAD_FILE", file=sys.stderr)
        return 64
    base_path = Path(argv[1])
    head_path = Path(argv[2])
    base_text = base_path.read_text(encoding="utf-8") if base_path.is_file() else ""
    head_text = head_path.read_text(encoding="utf-8") if head_path.is_file() else ""

    base_reqs = parse_requirements(base_text)
    head_reqs = parse_requirements(head_text)
    base_cov = parse_coverage(base_text)
    head_cov = parse_coverage(head_text)

    sys.stdout.write(render_diff(base_reqs, head_reqs, base_cov, head_cov))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
