#!/usr/bin/env python3
"""Generate apps/gest/_generated/dora.md — the four DORA metrics computed from GitHub
Actions deploy history. Deterministic: same history in, same markdown out.

Definitions (mapped to this repo's reality):
  - Deployment frequency : successful runs of the deploy workflows per week
  - Lead time for changes: commit timestamp -> deploy-success timestamp, median
  - Change failure rate  : failed deploy runs / total deploy runs
  - MTTR                 : failed deploy -> next successful deploy of the same workflow, median

NOT in the pre-commit loop (network + gh auth): run via `make dora`, typically monthly or
before a CDA/case-study checkpoint. The case study (Q1 2027) wants this series started
early — "from zero deploys to N/week" needs the zero on record.
"""
import argparse
import json
import statistics
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Housetree defaults; overridable on the CLI so the same generator can compute DORA
# for any repo whose deploys run as named GitHub Actions workflows.
# TODO(phase1): deploy-workflow identification is intrinsically project-specific
# (workflow names differ per repo / CI provider). A framework adapter should
# discover them rather than take them as flags.
DEFAULT_REPO = "housetreespa-it/housetree"
DEFAULT_WORKFLOWS = ["deploy gest (staging)", "deploy gest (prod)"]
DEFAULT_OUT = Path(__file__).resolve().parent.parent / "apps/gest/_generated/dora.md"

REPO = DEFAULT_REPO
WORKFLOWS = DEFAULT_WORKFLOWS
OUT = DEFAULT_OUT


def gh_runs(workflow: str) -> list[dict]:
    out = subprocess.run(
        ["gh", "api", f"repos/{REPO}/actions/runs",
         "-X", "GET", "-f", "per_page=100", "--paginate",
         "--jq", f'.workflow_runs[] | select(.name == "{workflow}") '
                 '| {status: .conclusion, created: .created_at, finished: .updated_at, head_ts: .head_commit.timestamp}'],
        capture_output=True, text=True, check=True)
    return [json.loads(line) for line in out.stdout.splitlines() if line.strip()]


def iso(ts: str) -> datetime:
    return datetime.fromisoformat(ts.replace("Z", "+00:00"))


def fmt_td(seconds: float) -> str:
    if seconds < 3600:
        return f"{seconds / 60:.0f} min"
    if seconds < 86400:
        return f"{seconds / 3600:.1f} h"
    return f"{seconds / 86400:.1f} d"


def metrics(runs: list[dict]) -> dict:
    done = [r for r in runs if r["status"] in ("success", "failure")]
    if not done:
        return {"deploys": 0}
    done.sort(key=lambda r: r["created"])
    ok = [r for r in done if r["status"] == "success"]
    ko = [r for r in done if r["status"] == "failure"]

    first, last = iso(done[0]["created"]), iso(done[-1]["created"])
    weeks = max((last - first).total_seconds() / (7 * 86400), 1 / 7)

    # lead time = head commit -> run END (updated_at). Using created_at (run START)
    # yields a flattering-but-fake 0 min on push-triggered deploys.
    lead_times = [
        (iso(r["finished"]) - iso(r["head_ts"])).total_seconds()
        for r in ok if r.get("head_ts") and r.get("finished")
    ]
    # MTTR: for each failure, time to the next success
    mttrs = []
    for f in ko:
        nxt = next((s for s in ok if s["created"] > f["created"]), None)
        if nxt:
            mttrs.append((iso(nxt["finished"]) - iso(f["finished"])).total_seconds())

    return {
        "deploys": len(ok),
        "failures": len(ko),
        "freq_per_week": len(ok) / weeks,
        "lead_time": fmt_td(statistics.median(lead_times)) if lead_times else "n/a",
        "cfr": f"{len(ko) / len(done) * 100:.0f}%",
        "mttr": fmt_td(statistics.median(mttrs)) if mttrs else "n/a (no failure or none recovered)",
        "since": first.date().isoformat(),
    }


def main() -> int:
    global REPO, WORKFLOWS, OUT
    ap = argparse.ArgumentParser(description="Compute DORA metrics from GitHub Actions deploy history.")
    ap.add_argument("--repo", default=DEFAULT_REPO, help="owner/name of the GitHub repo")
    ap.add_argument("--workflow", action="append", dest="workflows",
                    help="deploy workflow name (repeatable); defaults to the housetree deploy workflows")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="output markdown path")
    ap.add_argument("--label", default="apps/gest", help="human label for the doc title")
    args = ap.parse_args()
    REPO = args.repo
    WORKFLOWS = args.workflows if args.workflows else DEFAULT_WORKFLOWS
    OUT = Path(args.out)
    lines = [
        f"# DORA metrics — {args.label}",
        "",
        f"Auto-generated by `make dora` ({datetime.now(timezone.utc).date().isoformat()}). "
        "Source: GitHub Actions deploy-workflow history. NOT regenerated by pre-commit "
        "(needs network + gh auth); refresh monthly or before a reporting checkpoint.",
        "",
        "| Workflow | Deploys | Freq/week | Lead time (median) | Change failure rate | MTTR (median) | Since |",
        "|---|---|---|---|---|---|---|",
    ]
    for wf in WORKFLOWS:
        m = metrics(gh_runs(wf))
        if m["deploys"] == 0 and m.get("failures", 0) == 0:
            lines.append(f"| {wf} | 0 | — | — | — | — | — |")
        else:
            lines.append(
                f"| {wf} | {m['deploys']} | {m['freq_per_week']:.1f} | {m['lead_time']} "
                f"| {m['cfr']} | {m['mttr']} | {m['since']} |")
    lines += [
        "",
        "Definitions: deployment frequency = successful deploy runs/week; lead time = head-commit",
        "timestamp → deploy success (median); CFR = failed/total deploy runs; MTTR = failed deploy",
        "→ next successful deploy (median).",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
